# Intended for use on a Raspberry Pi 3 (model B)
FROM python:2

COPY ./requirements.txt /app/
RUN pip install -r /app/requirements.txt

CMD python /app/lightwave_link.py
WORKDIR /app/

# Do this last, as script is still in development and changes often
COPY ./lightwave_link.py ./config.yml /app/
