{
 "title": "LightwaveRF Heating",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Room",
    "query": "query_result({job=\"lwl\",product=\"valve\"})"
   },
   {
    "name": "Switch",
    "query": "query_result({job=\"lwl\",product=\"electr\"})"
   }
  ]
 },
 "panels": [
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$Switch",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "repeat": "Switch",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_output_ratio{name=\"Boiler switch\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 0, "y": 3 },
   "repeat": "Room",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 3.4285714285714284, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 6.857142857142857, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 10.285714285714285, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 13.714285714285714, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 17.142857142857142, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 20.57142857142857, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 0, "y": 6 },
   "repeat": "Room",
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"} - (lwl_target_celsius{name=\"$Room\"} > 0)"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 3.4285714285714284, "y": 6 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"} - (lwl_target_celsius{name=\"$Room\"} > 0)"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 6.857142857142857, "y": 6 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"} - (lwl_target_celsius{name=\"$Room\"} > 0)"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 10.285714285714285, "y": 6 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"} - (lwl_target_celsius{name=\"$Room\"} > 0)"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 13.714285714285714, "y": 6 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"} - (lwl_target_celsius{name=\"$Room\"} > 0)"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 17.142857142857142, "y": 6 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"} - (lwl_target_celsius{name=\"$Room\"} > 0)"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 20.57142857142857, "y": 6 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"} - (lwl_target_celsius{name=\"$Room\"} > 0)"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 0, "y": 9 },
   "repeat": "Room",
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_battery_volts{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 3.4285714285714284, "y": 9 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_battery_volts{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 6.857142857142857, "y": 9 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_battery_volts{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 10.285714285714285, "y": 9 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_battery_volts{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 13.714285714285714, "y": 9 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_battery_volts{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 17.142857142857142, "y": 9 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_battery_volts{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 20.57142857142857, "y": 9 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_battery_volts{name=\"$Room\"}"
    }
   ]
  },
  { "title": "Thermal History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$Room",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "repeat": "Room",
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"}",
     "legendFormat": "Actual Temperature"
    },
    {
     "expr": "lwl_target_celsius{name=\"$Room\"}",
     "legendFormat": "Target Temperature"
    },
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}",
     "legendFormat": "Output"
    },
    {
     "expr": "lwl_target_ratio{name=\"$Room\"}",
     "legendFormat": "Target Output"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"}",
     "legendFormat": "Actual Temperature"
    },
    {
     "expr": "lwl_target_celsius{name=\"$Room\"}",
     "legendFormat": "Target Temperature"
    },
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}",
     "legendFormat": "Output"
    },
    {
     "expr": "lwl_target_ratio{name=\"$Room\"}",
     "legendFormat": "Target Output"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"}",
     "legendFormat": "Actual Temperature"
    },
    {
     "expr": "lwl_target_celsius{name=\"$Room\"}",
     "legendFormat": "Target Temperature"
    },
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}",
     "legendFormat": "Output"
    },
    {
     "expr": "lwl_target_ratio{name=\"$Room\"}",
     "legendFormat": "Target Output"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"}",
     "legendFormat": "Actual Temperature"
    },
    {
     "expr": "lwl_target_celsius{name=\"$Room\"}",
     "legendFormat": "Target Temperature"
    },
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}",
     "legendFormat": "Output"
    },
    {
     "expr": "lwl_target_ratio{name=\"$Room\"}",
     "legendFormat": "Target Output"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"}",
     "legendFormat": "Actual Temperature"
    },
    {
     "expr": "lwl_target_celsius{name=\"$Room\"}",
     "legendFormat": "Target Temperature"
    },
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}",
     "legendFormat": "Output"
    },
    {
     "expr": "lwl_target_ratio{name=\"$Room\"}",
     "legendFormat": "Target Output"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"}",
     "legendFormat": "Actual Temperature"
    },
    {
     "expr": "lwl_target_celsius{name=\"$Room\"}",
     "legendFormat": "Target Temperature"
    },
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}",
     "legendFormat": "Output"
    },
    {
     "expr": "lwl_target_ratio{name=\"$Room\"}",
     "legendFormat": "Target Output"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"}",
     "legendFormat": "Actual Temperature"
    },
    {
     "expr": "lwl_target_celsius{name=\"$Room\"}",
     "legendFormat": "Target Temperature"
    },
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}",
     "legendFormat": "Output"
    },
    {
     "expr": "lwl_target_ratio{name=\"$Room\"}",
     "legendFormat": "Target Output"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Call for heat: Switching on",
     "type": "graph",
     "description": "When one or more valves are calling for heat, there must be at least one switch calling for heat (i.e. the boiler switch)",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(lwl_output_ratio{product=\"valve\"} > 0)",
       "legendFormat": "Valves"
      },
      {
       "expr": "count(lwl_output_ratio{product=\"electr\"} > 0)",
       "legendFormat": "Switches"
      }
     ]
    },
    {
     "title": "Call for heat: Switching off",
     "type": "graph",
     "description": "When no valves are calling for heat, there must be any switch calling for heat (i.e. the boiler switch)",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(lwl_output_ratio{product=\"valve\"} > 0)",
       "legendFormat": "Valves"
      },
      {
       "expr": "count(lwl_output_ratio{product=\"electr\"} > 0)",
       "legendFormat": "Switches"
      }
     ]
    },
    {
     "title": "Low battery",
     "type": "graph",
     "gridPos": { "h": 6, "w": 20, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "volt" }
     ],
     "targets": [
      {
       "expr": "lwl_battery_volts{product=\"valve\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}